import '../../../../core/domain/failure.dart';
import '../../../../core/domain/result.dart';
import '../../domain/entities/quest.dart';
import '../../domain/repositories/quest_repository.dart';
import '../../domain/services/quest_input_validator.dart';
import '../id_generator.dart';
import '../models/create_quest_command.dart';

/// Creates a new [Quest]: validates the input, assigns a fresh id via the
/// injected [IdGenerator] (never generated by the caller/widget), and
/// persists exactly once through [QuestRepository.upsert]. Every field this
/// use case doesn't accept from [CreateQuestCommand] is set to the same
/// inert default every quest fixture in this codebase already uses —
/// quest-chain/identity/reward/deadline systems don't exist yet.
class CreateQuestUseCase {
  const CreateQuestUseCase({
    required QuestRepository questRepository,
    IdGenerator idGenerator = const UuidV4IdGenerator(),
    QuestInputValidator validator = const QuestInputValidator(),
  }) : _questRepository = questRepository,
       _idGenerator = idGenerator,
       _validator = validator;

  final QuestRepository _questRepository;
  final IdGenerator _idGenerator;
  final QuestInputValidator _validator;

  Future<Result<Quest>> execute(CreateQuestCommand command) async {
    final title = command.title.trim();
    final description = command.description.trim();

    final failure = _validator.validate(
      title: title,
      description: description,
      attributeXpWeights: command.attributeXpWeights,
      progressType: command.progressType,
      targetProgress: command.targetProgress,
    );
    if (failure != null) {
      return Err(failure);
    }

    final quest = Quest(
      id: _idGenerator.generate(),
      title: title,
      description: description,
      type: command.type,
      difficulty: command.difficulty,
      attributeXpWeights: command.attributeXpWeights,
      linkedIdentityStatementIds: const [],
      progressType: command.progressType,
      currentProgress: 0,
      targetProgress: command.targetProgress,
      prerequisiteQuestIds: const [],
      state: QuestCompletionState.notStarted,
      failureBehavior: FailureBehavior.expire,
      repeatability: command.repeatability,
    );

    try {
      await _questRepository.upsert(quest);
    } catch (e) {
      return Err(UnexpectedFailure('Failed to save quest: $e'));
    }

    return Ok(quest);
  }
}
