// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:prime/features/quests/data/models/quest_hive_model.dart';
import 'package:prime/features/quests/data/models/quest_progress_hive_model.dart';
import 'package:prime/features/xp_ledger/data/models/xp_transaction_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(QuestHiveModelAdapter());
    registerAdapter(QuestProgressHiveModelAdapter());
    registerAdapter(XpTransactionHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(QuestHiveModelAdapter());
    registerAdapter(QuestProgressHiveModelAdapter());
    registerAdapter(XpTransactionHiveModelAdapter());
  }
}
