import 'package:flutter/widgets.dart';

import '../../../l10n/app_localizations.dart';

/// ID-keyed lookup from `quest_suggestion_catalog.dart`'s stable
/// `QuestSuggestion.id` to its localized title/description/motivation —
/// deliberately not a duplicated catalog: the 82-entry catalog stays the
/// single source of truth for every non-text field (attribute weights,
/// progress type, visual key, ranking metadata...), and this is the one
/// place that maps an id to display text, per the "localized content lookup
/// keyed by stable ID" approach.
String suggestionTitle(BuildContext context, String suggestionId) {
  final l10n = AppLocalizations.of(context)!;
  return switch (suggestionId) {
    'study_pomodoro' => l10n.suggestionStudyPomodoroTitle,
    'review_lecture_notes' => l10n.suggestionReviewLectureNotesTitle,
    'solve_practice_questions' => l10n.suggestionSolvePracticeQuestionsTitle,
    'read_20_pages' => l10n.suggestionRead20PagesTitle,
    'prepare_tomorrows_task_list' =>
      l10n.suggestionPrepareTomorrowsTaskListTitle,
    'practice_english_15' => l10n.suggestionPracticeEnglish15Title,
    'plan_top_3_tasks' => l10n.suggestionPlanTop3TasksTitle,
    'finish_deep_work_block' => l10n.suggestionFinishDeepWorkBlockTitle,
    'clear_important_email' => l10n.suggestionClearImportantEmailTitle,
    'walk_15_break' => l10n.suggestionWalk15BreakTitle,
    'review_weekly_priorities' => l10n.suggestionReviewWeeklyPrioritiesTitle,
    'learn_job_concept' => l10n.suggestionLearnJobConceptTitle,
    'review_weekly_numbers' => l10n.suggestionReviewWeeklyNumbersTitle,
    'reach_out_one_customer' => l10n.suggestionReachOutOneCustomerTitle,
    'write_top_priority' => l10n.suggestionWriteTopPriorityTitle,
    'review_cash_runway' => l10n.suggestionReviewCashRunwayTitle,
    'batch_process_invoices' => l10n.suggestionBatchProcessInvoicesTitle,
    'read_industry_article' => l10n.suggestionReadIndustryArticleTitle,
    'plan_weekly_meals' => l10n.suggestionPlanWeeklyMealsTitle,
    'tidy_sprint_10' => l10n.suggestionTidySprint10Title,
    'prep_tomorrows_lunch' => l10n.suggestionPrepTomorrowsLunchTitle,
    'call_family_member' => l10n.suggestionCallFamilyMemberTitle,
    'declutter_one_drawer' => l10n.suggestionDeclutterOneDrawerTitle,
    'batch_cook_meal' => l10n.suggestionBatchCookMealTitle,
    'gentle_walk_15' => l10n.suggestionGentleWalk15Title,
    'call_old_friend' => l10n.suggestionCallOldFriendTitle,
    'read_chapter_pleasure' => l10n.suggestionReadChapterPleasureTitle,
    'try_new_simple_recipe' => l10n.suggestionTryNewSimpleRecipeTitle,
    'journal_evening' => l10n.suggestionJournalEveningTitle,
    'learn_new_word' => l10n.suggestionLearnNewWordTitle,
    'walk_20' => l10n.suggestionWalk20Title,
    'full_body_workout' => l10n.suggestionFullBodyWorkoutTitle,
    'pushups_20' => l10n.suggestionPushups20Title,
    'stretch_10' => l10n.suggestionStretch10Title,
    'drink_water_8' => l10n.suggestionDrinkWater8Title,
    'high_protein_meal' => l10n.suggestionHighProteinMealTitle,
    'mobility_5' => l10n.suggestionMobility5Title,
    'take_the_stairs' => l10n.suggestionTakeTheStairsTitle,
    'extra_vegetable_serving' => l10n.suggestionExtraVegetableServingTitle,
    'cook_at_home' => l10n.suggestionCookAtHomeTitle,
    'avoid_added_sugar' => l10n.suggestionAvoidAddedSugarTitle,
    'meal_prep_tomorrow' => l10n.suggestionMealPrepTomorrowTitle,
    'track_todays_meals' => l10n.suggestionTrackTodaysMealsTitle,
    'consistent_wakeup' => l10n.suggestionConsistentWakeupTitle,
    'no_screens_before_bed' => l10n.suggestionNoScreensBeforeBedTitle,
    'sleep_before_time' => l10n.suggestionSleepBeforeTimeTitle,
    'nap_20' => l10n.suggestionNap20Title,
    'wind_down_with_book' => l10n.suggestionWindDownWithBookTitle,
    'read_one_article' => l10n.suggestionReadOneArticleTitle,
    'finish_one_chapter' => l10n.suggestionFinishOneChapterTitle,
    'read_before_bed' => l10n.suggestionReadBeforeBedTitle,
    'audiobook_chapter' => l10n.suggestionAudiobookChapterTitle,
    'meditate_10' => l10n.suggestionMeditate10Title,
    'deep_breathing_5' => l10n.suggestionDeepBreathing5Title,
    'body_scan' => l10n.suggestionBodyScanTitle,
    'sit_in_silence_5' => l10n.suggestionSitInSilence5Title,
    'gratitude_three' => l10n.suggestionGratitudeThreeTitle,
    'mindful_walk_no_phone' => l10n.suggestionMindfulWalkNoPhoneTitle,
    'log_todays_spending' => l10n.suggestionLogTodaysSpendingTitle,
    'review_subscription' => l10n.suggestionReviewSubscriptionTitle,
    'move_to_savings' => l10n.suggestionMoveToSavingsTitle,
    'check_weekly_budget' => l10n.suggestionCheckWeeklyBudgetTitle,
    'read_finance_article' => l10n.suggestionReadFinanceArticleTitle,
    'thoughtful_message' => l10n.suggestionThoughtfulMessageTitle,
    'phone_free_meal' => l10n.suggestionPhoneFreeMealTitle,
    'note_of_appreciation' => l10n.suggestionNoteOfAppreciationTitle,
    'plan_get_together' => l10n.suggestionPlanGetTogetherTitle,
    'ask_about_their_day' => l10n.suggestionAskAboutTheirDayTitle,
    'clear_inbox_zero' => l10n.suggestionClearInboxZeroTitle,
    'plan_tomorrow_morning' => l10n.suggestionPlanTomorrowMorningTitle,
    'organize_desktop_files' => l10n.suggestionOrganizeDesktopFilesTitle,
    'sketch_10' => l10n.suggestionSketch10Title,
    'write_200_words' => l10n.suggestionWrite200WordsTitle,
    'learn_3_chords' => l10n.suggestionLearn3ChordsTitle,
    'creative_photo' => l10n.suggestionCreativePhotoTitle,
    'brainstorm_10_ideas' => l10n.suggestionBrainstorm10IdeasTitle,
    'phone_free_20' => l10n.suggestionPhoneFree20Title,
    'relaxing_bath' => l10n.suggestionRelaxingBathTitle,
    'fresh_air_break' => l10n.suggestionFreshAirBreakTitle,
    'say_no_once' => l10n.suggestionSayNoOnceTitle,
    'small_kind_treat' => l10n.suggestionSmallKindTreatTitle,
    'tidy_one_area' => l10n.suggestionTidyOneAreaTitle,
    _ => suggestionId,
  };
}

String suggestionDescription(BuildContext context, String suggestionId) {
  final l10n = AppLocalizations.of(context)!;
  return switch (suggestionId) {
    'study_pomodoro' => l10n.suggestionStudyPomodoroDesc,
    'review_lecture_notes' => l10n.suggestionReviewLectureNotesDesc,
    'solve_practice_questions' => l10n.suggestionSolvePracticeQuestionsDesc,
    'read_20_pages' => l10n.suggestionRead20PagesDesc,
    'prepare_tomorrows_task_list' =>
      l10n.suggestionPrepareTomorrowsTaskListDesc,
    'practice_english_15' => l10n.suggestionPracticeEnglish15Desc,
    'plan_top_3_tasks' => l10n.suggestionPlanTop3TasksDesc,
    'finish_deep_work_block' => l10n.suggestionFinishDeepWorkBlockDesc,
    'clear_important_email' => l10n.suggestionClearImportantEmailDesc,
    'walk_15_break' => l10n.suggestionWalk15BreakDesc,
    'review_weekly_priorities' => l10n.suggestionReviewWeeklyPrioritiesDesc,
    'learn_job_concept' => l10n.suggestionLearnJobConceptDesc,
    'review_weekly_numbers' => l10n.suggestionReviewWeeklyNumbersDesc,
    'reach_out_one_customer' => l10n.suggestionReachOutOneCustomerDesc,
    'write_top_priority' => l10n.suggestionWriteTopPriorityDesc,
    'review_cash_runway' => l10n.suggestionReviewCashRunwayDesc,
    'batch_process_invoices' => l10n.suggestionBatchProcessInvoicesDesc,
    'read_industry_article' => l10n.suggestionReadIndustryArticleDesc,
    'plan_weekly_meals' => l10n.suggestionPlanWeeklyMealsDesc,
    'tidy_sprint_10' => l10n.suggestionTidySprint10Desc,
    'prep_tomorrows_lunch' => l10n.suggestionPrepTomorrowsLunchDesc,
    'call_family_member' => l10n.suggestionCallFamilyMemberDesc,
    'declutter_one_drawer' => l10n.suggestionDeclutterOneDrawerDesc,
    'batch_cook_meal' => l10n.suggestionBatchCookMealDesc,
    'gentle_walk_15' => l10n.suggestionGentleWalk15Desc,
    'call_old_friend' => l10n.suggestionCallOldFriendDesc,
    'read_chapter_pleasure' => l10n.suggestionReadChapterPleasureDesc,
    'try_new_simple_recipe' => l10n.suggestionTryNewSimpleRecipeDesc,
    'journal_evening' => l10n.suggestionJournalEveningDesc,
    'learn_new_word' => l10n.suggestionLearnNewWordDesc,
    'walk_20' => l10n.suggestionWalk20Desc,
    'full_body_workout' => l10n.suggestionFullBodyWorkoutDesc,
    'pushups_20' => l10n.suggestionPushups20Desc,
    'stretch_10' => l10n.suggestionStretch10Desc,
    'drink_water_8' => l10n.suggestionDrinkWater8Desc,
    'high_protein_meal' => l10n.suggestionHighProteinMealDesc,
    'mobility_5' => l10n.suggestionMobility5Desc,
    'take_the_stairs' => l10n.suggestionTakeTheStairsDesc,
    'extra_vegetable_serving' => l10n.suggestionExtraVegetableServingDesc,
    'cook_at_home' => l10n.suggestionCookAtHomeDesc,
    'avoid_added_sugar' => l10n.suggestionAvoidAddedSugarDesc,
    'meal_prep_tomorrow' => l10n.suggestionMealPrepTomorrowDesc,
    'track_todays_meals' => l10n.suggestionTrackTodaysMealsDesc,
    'consistent_wakeup' => l10n.suggestionConsistentWakeupDesc,
    'no_screens_before_bed' => l10n.suggestionNoScreensBeforeBedDesc,
    'sleep_before_time' => l10n.suggestionSleepBeforeTimeDesc,
    'nap_20' => l10n.suggestionNap20Desc,
    'wind_down_with_book' => l10n.suggestionWindDownWithBookDesc,
    'read_one_article' => l10n.suggestionReadOneArticleDesc,
    'finish_one_chapter' => l10n.suggestionFinishOneChapterDesc,
    'read_before_bed' => l10n.suggestionReadBeforeBedDesc,
    'audiobook_chapter' => l10n.suggestionAudiobookChapterDesc,
    'meditate_10' => l10n.suggestionMeditate10Desc,
    'deep_breathing_5' => l10n.suggestionDeepBreathing5Desc,
    'body_scan' => l10n.suggestionBodyScanDesc,
    'sit_in_silence_5' => l10n.suggestionSitInSilence5Desc,
    'gratitude_three' => l10n.suggestionGratitudeThreeDesc,
    'mindful_walk_no_phone' => l10n.suggestionMindfulWalkNoPhoneDesc,
    'log_todays_spending' => l10n.suggestionLogTodaysSpendingDesc,
    'review_subscription' => l10n.suggestionReviewSubscriptionDesc,
    'move_to_savings' => l10n.suggestionMoveToSavingsDesc,
    'check_weekly_budget' => l10n.suggestionCheckWeeklyBudgetDesc,
    'read_finance_article' => l10n.suggestionReadFinanceArticleDesc,
    'thoughtful_message' => l10n.suggestionThoughtfulMessageDesc,
    'phone_free_meal' => l10n.suggestionPhoneFreeMealDesc,
    'note_of_appreciation' => l10n.suggestionNoteOfAppreciationDesc,
    'plan_get_together' => l10n.suggestionPlanGetTogetherDesc,
    'ask_about_their_day' => l10n.suggestionAskAboutTheirDayDesc,
    'clear_inbox_zero' => l10n.suggestionClearInboxZeroDesc,
    'plan_tomorrow_morning' => l10n.suggestionPlanTomorrowMorningDesc,
    'organize_desktop_files' => l10n.suggestionOrganizeDesktopFilesDesc,
    'sketch_10' => l10n.suggestionSketch10Desc,
    'write_200_words' => l10n.suggestionWrite200WordsDesc,
    'learn_3_chords' => l10n.suggestionLearn3ChordsDesc,
    'creative_photo' => l10n.suggestionCreativePhotoDesc,
    'brainstorm_10_ideas' => l10n.suggestionBrainstorm10IdeasDesc,
    'phone_free_20' => l10n.suggestionPhoneFree20Desc,
    'relaxing_bath' => l10n.suggestionRelaxingBathDesc,
    'fresh_air_break' => l10n.suggestionFreshAirBreakDesc,
    'say_no_once' => l10n.suggestionSayNoOnceDesc,
    'small_kind_treat' => l10n.suggestionSmallKindTreatDesc,
    'tidy_one_area' => l10n.suggestionTidyOneAreaDesc,
    _ => '',
  };
}

/// Only `study_pomodoro` currently has motivation copy in the catalog — every
/// other id falls through to `null`, matching `QuestSuggestion.motivation`'s
/// own optionality.
String? suggestionMotivation(BuildContext context, String suggestionId) {
  final l10n = AppLocalizations.of(context)!;
  return switch (suggestionId) {
    'study_pomodoro' => l10n.suggestionStudyPomodoroMotivation,
    _ => null,
  };
}
