import '../../../../core/domain/attribute_type.dart';
import '../../../quests/domain/entities/quest.dart';
import '../../../quests/domain/entities/repeatability.dart';
import '../entities/quest_suggestion.dart';
import '../entities/recommendation_profile.dart';

/// Phase 16 — code-defined quest suggestion catalog. No AI, no network: this
/// is the entire recommendation surface, ranked deterministically by
/// `SuggestionRankingPolicy` against a `RecommendationProfile`.
///
/// [GoalArea] has more categories (12) than [AttributeType] has attributes
/// (8) — `creativity`, `selfCare`, `organization`, and `sleep` have no
/// dedicated attribute of their own. Each is mapped onto the closest
/// existing attribute below rather than growing the 8-attribute system for
/// this phase: `organization` → discipline, `sleep`/`selfCare`/`creativity`
/// → mindfulness. This only affects which attribute earns XP; the
/// suggestion's [GoalArea] tags (used for matching/filtering) are unaffected.
///
/// Grouped by the life-stage-specific sections the phase brief called out
/// (student/working professional/entrepreneur/homemaker/retired) followed by
/// universal goal-area sections (fitness/nutrition/sleep/reading/mindfulness/
/// finance/relationships/organization/creativity/self-care) that apply
/// regardless of life stage — `lifeStages: {}` on those means "universal,"
/// see `QuestSuggestion.lifeStages`.
const questSuggestionCatalog = <QuestSuggestion>[
  // ── Student ─────────────────────────────────────────────────────────
  QuestSuggestion(
    id: 'study_pomodoro',
    title: 'Study one focused Pomodoro',
    description: '25 minutes of distraction-free study, one clean block.',
    motivation: 'Small focused blocks beat long, unfocused sessions.',
    lifeStages: {LifeStage.student},
    goals: {GoalArea.study},
    attributeXpWeights: {AttributeType.knowledge: 30},
    type: QuestType.daily,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.duration,
    targetProgress: 25,
    estimatedMinutes: 25,
    visualKey: 'study/pomodoro',
    sortPriority: 10,
  ),
  QuestSuggestion(
    id: 'review_lecture_notes',
    title: "Review today's lecture notes",
    description: "Go back over what you covered today while it's fresh.",
    lifeStages: {LifeStage.student},
    goals: {GoalArea.study, GoalArea.organization},
    attributeXpWeights: {AttributeType.knowledge: 25},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 10,
    visualKey: 'study/review_notes',
    sortPriority: 20,
  ),
  QuestSuggestion(
    id: 'solve_practice_questions',
    title: 'Solve 10 practice questions',
    description: 'Active recall on 10 problems from your current subject.',
    lifeStages: {LifeStage.student},
    goals: {GoalArea.study},
    attributeXpWeights: {
      AttributeType.knowledge: 30,
      AttributeType.discipline: 10,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.quantity,
    targetProgress: 10,
    estimatedMinutes: 20,
    visualKey: 'study/practice_questions',
    sortPriority: 30,
  ),
  QuestSuggestion(
    id: 'read_20_pages',
    title: 'Read 20 pages',
    description: 'Textbook, novel, or anything worth finishing.',
    lifeStages: {LifeStage.student},
    goals: {GoalArea.study, GoalArea.reading},
    attributeXpWeights: {AttributeType.knowledge: 25},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.quantity,
    targetProgress: 20,
    estimatedMinutes: 20,
    visualKey: 'reading/pages_20',
    sortPriority: 40,
  ),
  QuestSuggestion(
    id: 'prepare_tomorrows_task_list',
    title: "Prepare tomorrow's task list",
    description: 'A few minutes tonight to walk into tomorrow with a plan.',
    lifeStages: {LifeStage.student},
    goals: {GoalArea.organization, GoalArea.study},
    attributeXpWeights: {AttributeType.discipline: 20},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 5,
    visualKey: 'organization/task_list',
    sortPriority: 50,
  ),
  QuestSuggestion(
    id: 'practice_english_15',
    title: 'Practice English for 15 minutes',
    description: 'Vocabulary, listening, or conversation practice.',
    lifeStages: {LifeStage.student},
    goals: {GoalArea.study, GoalArea.creativity},
    attributeXpWeights: {AttributeType.knowledge: 25},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.duration,
    targetProgress: 15,
    estimatedMinutes: 15,
    visualKey: 'study/language_practice',
    sortPriority: 60,
  ),

  // ── Working professional ────────────────────────────────────────────
  QuestSuggestion(
    id: 'plan_top_3_tasks',
    title: 'Plan the top 3 tasks',
    description: 'Before the day gets noisy, decide what actually matters.',
    lifeStages: {LifeStage.workingProfessional},
    goals: {GoalArea.career, GoalArea.organization},
    attributeXpWeights: {
      AttributeType.discipline: 20,
      AttributeType.career: 15,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 5,
    visualKey: 'career/top3',
    sortPriority: 70,
  ),
  QuestSuggestion(
    id: 'finish_deep_work_block',
    title: 'Finish one deep-work block',
    description: '60 minutes, one task, notifications off.',
    lifeStages: {LifeStage.workingProfessional},
    goals: {GoalArea.career},
    attributeXpWeights: {
      AttributeType.career: 35,
      AttributeType.discipline: 15,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.hard,
    progressType: ProgressType.duration,
    targetProgress: 60,
    estimatedMinutes: 60,
    visualKey: 'career/deep_work',
    sortPriority: 80,
  ),
  QuestSuggestion(
    id: 'clear_important_email',
    title: 'Clear the most important email',
    description: "The one you've been putting off — just that one.",
    lifeStages: {LifeStage.workingProfessional},
    goals: {GoalArea.career, GoalArea.organization},
    attributeXpWeights: {AttributeType.career: 20},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 10,
    visualKey: 'career/inbox',
    sortPriority: 90,
  ),
  QuestSuggestion(
    id: 'walk_15_break',
    title: 'Take a 15-minute walk',
    description: 'Step away from the desk and reset.',
    lifeStages: {LifeStage.workingProfessional},
    goals: {GoalArea.career, GoalArea.fitness, GoalArea.mindfulness},
    attributeXpWeights: {AttributeType.health: 20},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.duration,
    targetProgress: 15,
    estimatedMinutes: 15,
    visualKey: 'fitness/walk_15',
    sortPriority: 100,
  ),
  QuestSuggestion(
    id: 'review_weekly_priorities',
    title: 'Review weekly priorities',
    description: 'A short check-in on whether this week is still on track.',
    lifeStages: {LifeStage.workingProfessional},
    goals: {GoalArea.career, GoalArea.organization},
    attributeXpWeights: {
      AttributeType.career: 20,
      AttributeType.discipline: 10,
    },
    type: QuestType.weekly,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 10,
    visualKey: 'career/weekly_review',
    sortPriority: 110,
  ),
  QuestSuggestion(
    id: 'learn_job_concept',
    title: 'Learn one job-related concept',
    description: 'Read, watch, or practice one thing that improves your work.',
    lifeStages: {LifeStage.workingProfessional},
    goals: {GoalArea.career, GoalArea.study},
    attributeXpWeights: {AttributeType.career: 25, AttributeType.knowledge: 15},
    type: QuestType.daily,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 15,
    visualKey: 'career/learn_concept',
    sortPriority: 120,
  ),

  // ── Entrepreneur ─────────────────────────────────────────────────────
  QuestSuggestion(
    id: 'review_weekly_numbers',
    title: "Review this week's numbers",
    description: 'Revenue, costs, or usage — whatever tells you the truth.',
    lifeStages: {LifeStage.entrepreneur},
    goals: {GoalArea.finance, GoalArea.career},
    attributeXpWeights: {AttributeType.finance: 25, AttributeType.career: 15},
    type: QuestType.weekly,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 15,
    visualKey: 'finance/weekly_numbers',
    sortPriority: 130,
  ),
  QuestSuggestion(
    id: 'reach_out_one_customer',
    title: 'Reach out to one potential customer',
    description: 'One real conversation moves things more than a dozen plans.',
    lifeStages: {LifeStage.entrepreneur},
    goals: {GoalArea.career},
    attributeXpWeights: {AttributeType.career: 30},
    type: QuestType.daily,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 10,
    visualKey: 'career/outreach',
    sortPriority: 140,
  ),
  QuestSuggestion(
    id: 'write_top_priority',
    title: "Write down today's top priority",
    description: 'One sentence: what actually matters today.',
    lifeStages: {LifeStage.entrepreneur},
    goals: {GoalArea.organization, GoalArea.career},
    attributeXpWeights: {AttributeType.discipline: 15},
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 3,
    visualKey: 'organization/top_priority',
    sortPriority: 150,
  ),
  QuestSuggestion(
    id: 'review_cash_runway',
    title: 'Review cash runway',
    description: 'A few minutes with the numbers avoids surprises later.',
    lifeStages: {LifeStage.entrepreneur},
    goals: {GoalArea.finance},
    attributeXpWeights: {AttributeType.finance: 25},
    type: QuestType.weekly,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 15,
    visualKey: 'finance/runway',
    sortPriority: 160,
  ),
  QuestSuggestion(
    id: 'batch_process_invoices',
    title: 'Batch process invoices',
    description: 'Clear the paperwork in one sitting instead of piecemeal.',
    lifeStages: {LifeStage.entrepreneur},
    goals: {GoalArea.finance, GoalArea.organization},
    attributeXpWeights: {
      AttributeType.finance: 20,
      AttributeType.discipline: 10,
    },
    type: QuestType.weekly,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 20,
    visualKey: 'finance/invoices',
    sortPriority: 170,
  ),
  QuestSuggestion(
    id: 'read_industry_article',
    title: 'Read one industry article',
    description: "Stay current on the space you're building in.",
    lifeStages: {LifeStage.entrepreneur},
    goals: {GoalArea.career, GoalArea.study},
    attributeXpWeights: {AttributeType.career: 20, AttributeType.knowledge: 15},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 10,
    visualKey: 'career/industry_read',
    sortPriority: 180,
  ),

  // ── Homemaker ────────────────────────────────────────────────────────
  QuestSuggestion(
    id: 'plan_weekly_meals',
    title: "Plan this week's meals",
    description: 'Decide once, cook without decision fatigue all week.',
    lifeStages: {LifeStage.homemaker},
    goals: {GoalArea.organization, GoalArea.nutrition},
    attributeXpWeights: {AttributeType.discipline: 20},
    type: QuestType.weekly,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 15,
    visualKey: 'organization/meal_plan',
    sortPriority: 190,
  ),
  QuestSuggestion(
    id: 'tidy_sprint_10',
    title: 'Do a 10-minute tidy sprint',
    description: 'One timer, one room, no perfectionism.',
    lifeStages: {LifeStage.homemaker},
    goals: {GoalArea.organization},
    attributeXpWeights: {AttributeType.discipline: 15},
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.duration,
    targetProgress: 10,
    estimatedMinutes: 10,
    visualKey: 'organization/tidy_sprint',
    sortPriority: 200,
  ),
  QuestSuggestion(
    id: 'prep_tomorrows_lunch',
    title: "Prep tomorrow's lunch",
    description: 'Future you will be grateful.',
    lifeStages: {LifeStage.homemaker},
    goals: {GoalArea.organization, GoalArea.nutrition},
    attributeXpWeights: {AttributeType.discipline: 15},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 10,
    visualKey: 'nutrition/prep_lunch',
    sortPriority: 210,
  ),
  QuestSuggestion(
    id: 'call_family_member',
    title: 'Call a family member',
    description: 'A real conversation, not a text.',
    lifeStages: {LifeStage.homemaker},
    goals: {GoalArea.relationships},
    attributeXpWeights: {AttributeType.relationships: 25},
    type: QuestType.weekly,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 15,
    visualKey: 'relationships/call_family',
    sortPriority: 220,
  ),
  QuestSuggestion(
    id: 'declutter_one_drawer',
    title: 'Declutter one drawer',
    description: 'Small scope, real progress.',
    lifeStages: {LifeStage.homemaker},
    goals: {GoalArea.organization},
    attributeXpWeights: {AttributeType.discipline: 15},
    type: QuestType.weekly,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 15,
    visualKey: 'organization/declutter',
    sortPriority: 230,
  ),
  QuestSuggestion(
    id: 'batch_cook_meal',
    title: 'Batch-cook a meal',
    description: 'Cook once, eat well for days.',
    lifeStages: {LifeStage.homemaker},
    goals: {GoalArea.nutrition, GoalArea.organization},
    attributeXpWeights: {
      AttributeType.health: 20,
      AttributeType.discipline: 10,
    },
    type: QuestType.weekly,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 45,
    visualKey: 'nutrition/batch_cook',
    sortPriority: 240,
  ),

  // ── Retired ──────────────────────────────────────────────────────────
  QuestSuggestion(
    id: 'gentle_walk_15',
    title: 'Take a gentle 15-minute walk',
    description: 'Easy pace, fresh air, no pressure.',
    lifeStages: {LifeStage.retired},
    goals: {GoalArea.fitness, GoalArea.mindfulness},
    attributeXpWeights: {AttributeType.health: 20},
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.duration,
    targetProgress: 15,
    estimatedMinutes: 15,
    visualKey: 'fitness/gentle_walk',
    sortPriority: 250,
  ),
  QuestSuggestion(
    id: 'call_old_friend',
    title: 'Call an old friend',
    description: "Reconnect with someone you haven't spoken to in a while.",
    lifeStages: {LifeStage.retired},
    goals: {GoalArea.relationships},
    attributeXpWeights: {AttributeType.relationships: 25},
    type: QuestType.weekly,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 15,
    visualKey: 'relationships/old_friend',
    sortPriority: 260,
  ),
  QuestSuggestion(
    id: 'read_chapter_pleasure',
    title: 'Read a chapter for pleasure',
    description: 'No agenda — just a good book.',
    lifeStages: {LifeStage.retired},
    goals: {GoalArea.reading},
    attributeXpWeights: {AttributeType.knowledge: 20},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 15,
    visualKey: 'reading/chapter_pleasure',
    sortPriority: 270,
  ),
  QuestSuggestion(
    id: 'try_new_simple_recipe',
    title: 'Try a new simple recipe',
    description: "Cook something you've never made before.",
    lifeStages: {LifeStage.retired},
    goals: {GoalArea.nutrition, GoalArea.creativity},
    attributeXpWeights: {
      AttributeType.health: 15,
      AttributeType.mindfulness: 10,
    },
    type: QuestType.weekly,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 30,
    visualKey: 'nutrition/new_recipe',
    sortPriority: 280,
  ),
  QuestSuggestion(
    id: 'journal_evening',
    title: 'Write a journal entry about today',
    description: 'A few honest lines about how today went.',
    lifeStages: {LifeStage.retired},
    goals: {GoalArea.mindfulness, GoalArea.selfCare},
    attributeXpWeights: {AttributeType.mindfulness: 20},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 5,
    visualKey: 'mindfulness/journal_evening',
    sortPriority: 290,
  ),
  QuestSuggestion(
    id: 'learn_new_word',
    title: 'Learn one new word',
    description: 'Small, steady vocabulary growth.',
    lifeStages: {LifeStage.retired},
    goals: {GoalArea.study, GoalArea.reading},
    attributeXpWeights: {AttributeType.knowledge: 15},
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 3,
    visualKey: 'study/new_word',
    sortPriority: 300,
  ),

  // ── Fitness (universal) ─────────────────────────────────────────────
  QuestSuggestion(
    id: 'walk_20',
    title: 'Walk for 20 minutes',
    description: 'Any pace, anywhere — just get moving.',
    lifeStages: {},
    goals: {GoalArea.fitness},
    attributeXpWeights: {AttributeType.health: 25},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.duration,
    targetProgress: 20,
    estimatedMinutes: 20,
    visualKey: 'fitness/walk_20',
    sortPriority: 310,
  ),
  QuestSuggestion(
    id: 'full_body_workout',
    title: 'Complete a full-body workout',
    description: 'One real session, whatever equipment you have.',
    lifeStages: {},
    goals: {GoalArea.fitness},
    attributeXpWeights: {AttributeType.health: 30, AttributeType.strength: 25},
    type: QuestType.daily,
    difficulty: QuestDifficulty.hard,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 45,
    visualKey: 'fitness/full_body',
    sortPriority: 320,
  ),
  QuestSuggestion(
    id: 'pushups_20',
    title: 'Do 20 push-ups',
    description: 'Spread them across the day if you need to.',
    lifeStages: {},
    goals: {GoalArea.fitness},
    attributeXpWeights: {AttributeType.strength: 25},
    type: QuestType.daily,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.quantity,
    targetProgress: 20,
    estimatedMinutes: 5,
    visualKey: 'fitness/pushups',
    sortPriority: 330,
  ),
  QuestSuggestion(
    id: 'stretch_10',
    title: 'Stretch for 10 minutes',
    description: 'Loosen up, especially after sitting.',
    lifeStages: {},
    goals: {GoalArea.fitness, GoalArea.selfCare},
    attributeXpWeights: {AttributeType.health: 15},
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.duration,
    targetProgress: 10,
    estimatedMinutes: 10,
    visualKey: 'fitness/stretch',
    sortPriority: 340,
  ),
  QuestSuggestion(
    id: 'drink_water_8',
    title: 'Drink 8 glasses of water',
    description: 'Steady hydration through the day.',
    lifeStages: {},
    goals: {GoalArea.fitness, GoalArea.nutrition},
    attributeXpWeights: {AttributeType.health: 20},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.quantity,
    targetProgress: 8,
    estimatedMinutes: 5,
    visualKey: 'nutrition/water',
    sortPriority: 350,
  ),
  QuestSuggestion(
    id: 'high_protein_meal',
    title: 'Prepare a high-protein meal',
    description: 'Fuel your training properly.',
    lifeStages: {},
    goals: {GoalArea.fitness, GoalArea.nutrition},
    attributeXpWeights: {AttributeType.health: 20, AttributeType.strength: 10},
    type: QuestType.daily,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 20,
    visualKey: 'nutrition/protein_meal',
    sortPriority: 360,
  ),
  QuestSuggestion(
    id: 'mobility_5',
    title: 'Do a 5-minute mobility routine',
    description: 'Hips, shoulders, ankles — the joints that need it most.',
    lifeStages: {},
    goals: {GoalArea.fitness},
    attributeXpWeights: {AttributeType.health: 15},
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.duration,
    targetProgress: 5,
    estimatedMinutes: 5,
    visualKey: 'fitness/mobility',
    sortPriority: 370,
  ),
  QuestSuggestion(
    id: 'take_the_stairs',
    title: 'Take the stairs today',
    description: 'A small, repeatable choice that adds up.',
    lifeStages: {},
    goals: {GoalArea.fitness},
    attributeXpWeights: {AttributeType.health: 15, AttributeType.strength: 10},
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 2,
    visualKey: 'fitness/stairs',
    sortPriority: 380,
  ),

  // ── Nutrition (universal) ───────────────────────────────────────────
  QuestSuggestion(
    id: 'extra_vegetable_serving',
    title: 'Eat one extra serving of vegetables',
    description: "Add, don't restrict — just one more serving today.",
    lifeStages: {},
    goals: {GoalArea.nutrition},
    attributeXpWeights: {AttributeType.health: 15},
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 5,
    visualKey: 'nutrition/veggies',
    sortPriority: 390,
  ),
  QuestSuggestion(
    id: 'cook_at_home',
    title: 'Cook a meal at home instead of ordering',
    description: 'Control what goes in, save money too.',
    lifeStages: {},
    goals: {GoalArea.nutrition, GoalArea.finance},
    attributeXpWeights: {AttributeType.health: 20, AttributeType.finance: 10},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 30,
    visualKey: 'nutrition/cook_home',
    sortPriority: 400,
  ),
  QuestSuggestion(
    id: 'avoid_added_sugar',
    title: 'Avoid added sugar for the day',
    description: 'One full day, no added sugar.',
    lifeStages: {},
    goals: {GoalArea.nutrition},
    attributeXpWeights: {
      AttributeType.health: 20,
      AttributeType.discipline: 15,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 5,
    visualKey: 'nutrition/no_sugar',
    sortPriority: 410,
  ),
  QuestSuggestion(
    id: 'meal_prep_tomorrow',
    title: 'Meal-prep for tomorrow',
    description: "Set tomorrow's meals up tonight.",
    lifeStages: {},
    goals: {GoalArea.nutrition, GoalArea.organization},
    attributeXpWeights: {
      AttributeType.health: 15,
      AttributeType.discipline: 10,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 20,
    visualKey: 'nutrition/meal_prep',
    sortPriority: 420,
  ),
  QuestSuggestion(
    id: 'track_todays_meals',
    title: "Track today's meals",
    description: 'Just noticing what you eat changes how you eat.',
    lifeStages: {},
    goals: {GoalArea.nutrition},
    attributeXpWeights: {
      AttributeType.health: 15,
      AttributeType.discipline: 10,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 5,
    visualKey: 'nutrition/track_meals',
    sortPriority: 430,
  ),

  // ── Sleep (universal) ────────────────────────────────────────────────
  QuestSuggestion(
    id: 'consistent_wakeup',
    title: 'Set a consistent wake-up time',
    description: 'Same time every day, weekends included.',
    lifeStages: {},
    goals: {GoalArea.sleep},
    attributeXpWeights: {
      AttributeType.mindfulness: 20,
      AttributeType.discipline: 10,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 2,
    visualKey: 'sleep/wakeup',
    sortPriority: 440,
  ),
  QuestSuggestion(
    id: 'no_screens_before_bed',
    title: 'No screens 30 minutes before bed',
    description: 'Wind down without a backlit screen.',
    lifeStages: {},
    goals: {GoalArea.sleep},
    attributeXpWeights: {AttributeType.mindfulness: 20},
    type: QuestType.daily,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.duration,
    targetProgress: 30,
    estimatedMinutes: 30,
    visualKey: 'sleep/no_screens',
    sortPriority: 450,
  ),
  QuestSuggestion(
    id: 'sleep_before_time',
    title: 'Sleep before a chosen time',
    description: 'Pick a bedtime and actually hit it.',
    lifeStages: {},
    goals: {GoalArea.sleep},
    attributeXpWeights: {
      AttributeType.mindfulness: 20,
      AttributeType.discipline: 10,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 5,
    visualKey: 'sleep/bedtime',
    sortPriority: 460,
  ),
  QuestSuggestion(
    id: 'nap_20',
    title: 'Take a 20-minute nap',
    description: 'Short enough to stay refreshing, not groggy.',
    lifeStages: {},
    goals: {GoalArea.sleep, GoalArea.selfCare},
    attributeXpWeights: {
      AttributeType.mindfulness: 15,
      AttributeType.health: 10,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.duration,
    targetProgress: 20,
    estimatedMinutes: 20,
    visualKey: 'sleep/nap',
    sortPriority: 470,
  ),
  QuestSuggestion(
    id: 'wind_down_with_book',
    title: 'Wind down with a book instead of a screen',
    description: 'Trade the scroll for a few pages.',
    lifeStages: {},
    goals: {GoalArea.sleep, GoalArea.reading},
    attributeXpWeights: {
      AttributeType.mindfulness: 15,
      AttributeType.knowledge: 10,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.duration,
    targetProgress: 15,
    estimatedMinutes: 15,
    visualKey: 'sleep/wind_down_book',
    sortPriority: 480,
  ),

  // ── Reading (universal) ─────────────────────────────────────────────
  QuestSuggestion(
    id: 'read_one_article',
    title: 'Read one article on a new topic',
    description: 'Something outside your usual feed.',
    lifeStages: {},
    goals: {GoalArea.reading, GoalArea.study},
    attributeXpWeights: {AttributeType.knowledge: 20},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 10,
    visualKey: 'reading/article',
    sortPriority: 490,
  ),
  QuestSuggestion(
    id: 'finish_one_chapter',
    title: 'Finish one chapter',
    description: 'Keep the book moving, one chapter at a time.',
    lifeStages: {},
    goals: {GoalArea.reading},
    attributeXpWeights: {AttributeType.knowledge: 20},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 15,
    visualKey: 'reading/chapter',
    sortPriority: 500,
  ),
  QuestSuggestion(
    id: 'read_before_bed',
    title: 'Read before bed instead of scrolling',
    description: 'Swap the phone for a book at bedtime.',
    lifeStages: {},
    goals: {GoalArea.reading, GoalArea.sleep},
    attributeXpWeights: {
      AttributeType.knowledge: 15,
      AttributeType.mindfulness: 10,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 15,
    visualKey: 'reading/before_bed',
    sortPriority: 510,
  ),
  QuestSuggestion(
    id: 'audiobook_chapter',
    title: 'Listen to one audiobook chapter',
    description: 'Reading counts even with your ears.',
    lifeStages: {},
    goals: {GoalArea.reading},
    attributeXpWeights: {AttributeType.knowledge: 20},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 20,
    visualKey: 'reading/audiobook',
    sortPriority: 520,
  ),

  // ── Mindfulness (universal) ─────────────────────────────────────────
  QuestSuggestion(
    id: 'meditate_10',
    title: 'Meditate for 10 minutes',
    description: 'Sit, breathe, and let the noise settle.',
    lifeStages: {},
    goals: {GoalArea.mindfulness},
    attributeXpWeights: {AttributeType.mindfulness: 25},
    type: QuestType.daily,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.duration,
    targetProgress: 10,
    estimatedMinutes: 10,
    visualKey: 'mindfulness/meditate',
    sortPriority: 530,
  ),
  QuestSuggestion(
    id: 'deep_breathing_5',
    title: 'Practice 5 minutes of deep breathing',
    description: 'Slow, deliberate breaths — nothing else.',
    lifeStages: {},
    goals: {GoalArea.mindfulness},
    attributeXpWeights: {AttributeType.mindfulness: 15},
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.duration,
    targetProgress: 5,
    estimatedMinutes: 5,
    visualKey: 'mindfulness/breathing',
    sortPriority: 540,
  ),
  QuestSuggestion(
    id: 'body_scan',
    title: 'Do a short body scan',
    description: 'Notice tension from head to toe and let it go.',
    lifeStages: {},
    goals: {GoalArea.mindfulness},
    attributeXpWeights: {AttributeType.mindfulness: 15},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 10,
    visualKey: 'mindfulness/body_scan',
    sortPriority: 550,
  ),
  QuestSuggestion(
    id: 'sit_in_silence_5',
    title: 'Sit in silence for 5 minutes',
    description: 'No phone, no music — just quiet.',
    lifeStages: {},
    goals: {GoalArea.mindfulness, GoalArea.selfCare},
    attributeXpWeights: {AttributeType.mindfulness: 15},
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.duration,
    targetProgress: 5,
    estimatedMinutes: 5,
    visualKey: 'mindfulness/silence',
    sortPriority: 560,
  ),
  QuestSuggestion(
    id: 'gratitude_three',
    title: 'Practice gratitude — write 3 things down',
    description: 'Three specific things, however small.',
    lifeStages: {},
    goals: {GoalArea.mindfulness},
    attributeXpWeights: {AttributeType.mindfulness: 20},
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.quantity,
    targetProgress: 3,
    estimatedMinutes: 5,
    visualKey: 'mindfulness/gratitude',
    sortPriority: 570,
  ),
  QuestSuggestion(
    id: 'mindful_walk_no_phone',
    title: 'Do a mindful walk without your phone',
    description: 'Just you, moving, paying attention.',
    lifeStages: {},
    goals: {GoalArea.mindfulness, GoalArea.fitness},
    attributeXpWeights: {
      AttributeType.mindfulness: 15,
      AttributeType.health: 10,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 15,
    visualKey: 'mindfulness/mindful_walk',
    sortPriority: 580,
  ),

  // ── Finance (universal) ─────────────────────────────────────────────
  QuestSuggestion(
    id: 'log_todays_spending',
    title: "Log today's spending",
    description: 'A quick, honest record of where money went.',
    lifeStages: {},
    goals: {GoalArea.finance},
    attributeXpWeights: {AttributeType.finance: 20},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 5,
    visualKey: 'finance/log_spending',
    sortPriority: 590,
  ),
  QuestSuggestion(
    id: 'review_subscription',
    title: 'Review one subscription for cancellation',
    description: "Is it still worth what you're paying?",
    lifeStages: {},
    goals: {GoalArea.finance},
    attributeXpWeights: {AttributeType.finance: 20},
    type: QuestType.weekly,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 10,
    visualKey: 'finance/review_subscription',
    sortPriority: 600,
  ),
  QuestSuggestion(
    id: 'move_to_savings',
    title: 'Move a fixed amount into savings',
    description: 'Even a small amount, moved consistently.',
    lifeStages: {},
    goals: {GoalArea.finance},
    attributeXpWeights: {
      AttributeType.finance: 25,
      AttributeType.discipline: 10,
    },
    type: QuestType.weekly,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 5,
    visualKey: 'finance/save',
    sortPriority: 610,
  ),
  QuestSuggestion(
    id: 'check_weekly_budget',
    title: 'Check your budget for the week',
    description: 'A short look before spending gets away from you.',
    lifeStages: {},
    goals: {GoalArea.finance},
    attributeXpWeights: {AttributeType.finance: 20},
    type: QuestType.weekly,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 10,
    visualKey: 'finance/budget_check',
    sortPriority: 620,
  ),
  QuestSuggestion(
    id: 'read_finance_article',
    title: 'Read one article about personal finance',
    description: 'Build the knowledge, a little at a time.',
    lifeStages: {},
    goals: {GoalArea.finance, GoalArea.study},
    attributeXpWeights: {
      AttributeType.finance: 15,
      AttributeType.knowledge: 10,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 10,
    visualKey: 'finance/finance_read',
    sortPriority: 630,
  ),

  // ── Relationships (universal) ────────────────────────────────────────
  QuestSuggestion(
    id: 'thoughtful_message',
    title: 'Send a thoughtful message to a friend',
    description: 'Not a check-in — something real.',
    lifeStages: {},
    goals: {GoalArea.relationships},
    attributeXpWeights: {AttributeType.relationships: 20},
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 3,
    visualKey: 'relationships/message',
    sortPriority: 640,
  ),
  QuestSuggestion(
    id: 'phone_free_meal',
    title: 'Have a phone-free meal with someone',
    description: 'Full attention, one meal.',
    lifeStages: {},
    goals: {GoalArea.relationships, GoalArea.mindfulness},
    attributeXpWeights: {
      AttributeType.relationships: 20,
      AttributeType.mindfulness: 10,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 20,
    visualKey: 'relationships/phone_free_meal',
    sortPriority: 650,
  ),
  QuestSuggestion(
    id: 'note_of_appreciation',
    title: 'Write a note of appreciation',
    description: 'Tell someone specifically what you appreciate about them.',
    lifeStages: {},
    goals: {GoalArea.relationships},
    attributeXpWeights: {AttributeType.relationships: 20},
    type: QuestType.weekly,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 10,
    visualKey: 'relationships/appreciation',
    sortPriority: 660,
  ),
  QuestSuggestion(
    id: 'plan_get_together',
    title: 'Plan a get-together',
    description: 'Put something real on the calendar.',
    lifeStages: {},
    goals: {GoalArea.relationships},
    attributeXpWeights: {AttributeType.relationships: 25},
    type: QuestType.weekly,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 10,
    visualKey: 'relationships/get_together',
    sortPriority: 670,
  ),
  QuestSuggestion(
    id: 'ask_about_their_day',
    title: 'Ask a loved one about their day — and really listen',
    description: 'Give someone your full attention for a few minutes.',
    lifeStages: {},
    goals: {GoalArea.relationships},
    attributeXpWeights: {AttributeType.relationships: 15},
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 5,
    visualKey: 'relationships/ask_their_day',
    sortPriority: 680,
  ),

  // ── Organization (universal) ────────────────────────────────────────
  QuestSuggestion(
    id: 'clear_inbox_zero',
    title: 'Clear your inbox to zero',
    description: 'Archive, reply, or delete — until it is empty.',
    lifeStages: {},
    goals: {GoalArea.organization},
    attributeXpWeights: {AttributeType.discipline: 20},
    type: QuestType.weekly,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 20,
    visualKey: 'organization/inbox_zero',
    sortPriority: 690,
  ),
  QuestSuggestion(
    id: 'plan_tomorrow_morning',
    title: 'Plan tomorrow morning',
    description: 'Decide your first task before the day starts.',
    lifeStages: {},
    goals: {GoalArea.organization},
    attributeXpWeights: {AttributeType.discipline: 15},
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 5,
    visualKey: 'organization/plan_morning',
    sortPriority: 700,
  ),
  QuestSuggestion(
    id: 'organize_desktop_files',
    title: 'Organize your desktop files',
    description: 'Fifteen minutes of digital tidying.',
    lifeStages: {},
    goals: {GoalArea.organization},
    attributeXpWeights: {AttributeType.discipline: 15},
    type: QuestType.weekly,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.duration,
    targetProgress: 15,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 15,
    visualKey: 'organization/desktop_files',
    sortPriority: 710,
  ),

  // ── Creativity (universal) ──────────────────────────────────────────
  QuestSuggestion(
    id: 'sketch_10',
    title: 'Sketch for 10 minutes',
    description: 'No pressure to be good — just make marks.',
    lifeStages: {},
    goals: {GoalArea.creativity},
    attributeXpWeights: {AttributeType.mindfulness: 20},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.duration,
    targetProgress: 10,
    estimatedMinutes: 10,
    visualKey: 'creativity/sketch',
    sortPriority: 720,
  ),
  QuestSuggestion(
    id: 'write_200_words',
    title: 'Write 200 words of anything',
    description: 'Fiction, a journal, an idea — just write.',
    lifeStages: {},
    goals: {GoalArea.creativity},
    attributeXpWeights: {
      AttributeType.mindfulness: 15,
      AttributeType.knowledge: 10,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.quantity,
    targetProgress: 200,
    estimatedMinutes: 15,
    visualKey: 'creativity/write_words',
    sortPriority: 730,
  ),
  QuestSuggestion(
    id: 'learn_3_chords',
    title: 'Learn 3 chords on an instrument',
    description: 'Pick it up and make some noise.',
    lifeStages: {},
    goals: {GoalArea.creativity},
    attributeXpWeights: {
      AttributeType.mindfulness: 15,
      AttributeType.discipline: 10,
    },
    type: QuestType.weekly,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.quantity,
    targetProgress: 3,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 20,
    visualKey: 'creativity/three_chords',
    sortPriority: 740,
  ),
  QuestSuggestion(
    id: 'creative_photo',
    title: 'Take one creative photo',
    description: 'Look at something ordinary differently.',
    lifeStages: {},
    goals: {GoalArea.creativity},
    attributeXpWeights: {AttributeType.mindfulness: 15},
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 5,
    visualKey: 'creativity/photo',
    sortPriority: 750,
  ),
  QuestSuggestion(
    id: 'brainstorm_10_ideas',
    title: 'Brainstorm 10 ideas for a project',
    description: 'Quantity first — the good ones show up eventually.',
    lifeStages: {},
    goals: {GoalArea.creativity, GoalArea.career},
    attributeXpWeights: {
      AttributeType.mindfulness: 15,
      AttributeType.career: 10,
    },
    type: QuestType.weekly,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.quantity,
    targetProgress: 10,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 15,
    visualKey: 'creativity/brainstorm',
    sortPriority: 760,
  ),

  // ── Self-care (universal) ───────────────────────────────────────────
  QuestSuggestion(
    id: 'phone_free_20',
    title: 'Spend 20 minutes without the phone',
    description: 'Just be, without checking anything.',
    lifeStages: {},
    goals: {GoalArea.selfCare},
    attributeXpWeights: {AttributeType.mindfulness: 20},
    type: QuestType.daily,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.duration,
    targetProgress: 20,
    estimatedMinutes: 20,
    visualKey: 'selfcare/phone_free',
    sortPriority: 770,
  ),
  QuestSuggestion(
    id: 'relaxing_bath',
    title: 'Take a relaxing bath or shower',
    description: 'Unhurried, just for you.',
    lifeStages: {},
    goals: {GoalArea.selfCare},
    attributeXpWeights: {
      AttributeType.mindfulness: 15,
      AttributeType.health: 10,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 15,
    visualKey: 'selfcare/bath',
    sortPriority: 780,
  ),
  QuestSuggestion(
    id: 'fresh_air_break',
    title: 'Step outside for fresh air',
    description: 'A few minutes outside, no destination needed.',
    lifeStages: {},
    goals: {GoalArea.selfCare, GoalArea.mindfulness},
    attributeXpWeights: {
      AttributeType.mindfulness: 10,
      AttributeType.health: 10,
    },
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.duration,
    targetProgress: 5,
    estimatedMinutes: 5,
    visualKey: 'selfcare/fresh_air',
    sortPriority: 790,
  ),
  QuestSuggestion(
    id: 'say_no_once',
    title: 'Say no to one thing that drains you',
    description: 'Protect your time on purpose.',
    lifeStages: {},
    goals: {GoalArea.selfCare},
    attributeXpWeights: {
      AttributeType.mindfulness: 20,
      AttributeType.discipline: 10,
    },
    type: QuestType.weekly,
    difficulty: QuestDifficulty.normal,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 5,
    visualKey: 'selfcare/say_no',
    sortPriority: 800,
  ),
  QuestSuggestion(
    id: 'small_kind_treat',
    title: 'Treat yourself to something small and kind',
    description: 'A real, deliberate act of care for yourself.',
    lifeStages: {},
    goals: {GoalArea.selfCare},
    attributeXpWeights: {AttributeType.mindfulness: 15},
    type: QuestType.weekly,
    difficulty: QuestDifficulty.easy,
    progressType: ProgressType.binary,
    targetProgress: 1,
    repeatability: Repeatability.weekly,
    estimatedMinutes: 10,
    visualKey: 'selfcare/treat',
    sortPriority: 810,
  ),
  QuestSuggestion(
    id: 'tidy_one_area',
    title: 'Tidy one small area',
    description: 'One shelf, one corner — contained and doable.',
    lifeStages: {},
    goals: {GoalArea.selfCare, GoalArea.organization},
    attributeXpWeights: {AttributeType.discipline: 15},
    type: QuestType.daily,
    difficulty: QuestDifficulty.trivial,
    progressType: ProgressType.binary,
    targetProgress: 1,
    estimatedMinutes: 10,
    visualKey: 'selfcare/tidy_area',
    sortPriority: 820,
  ),
];
